#!/bin/sh
#
# valac wrapper to avoid glib dependency
#
# author: pancake <pancake@nopcode.org>
#
VERSION=0.1
POSIXVALADIR=include
MAIN=a.out
HAS_C=0
HAS_LC=0
SAVETEMPS=0
[ -z "${VALAC}" ] && VALAC=valac
[ -z "${CC}" ] && CC=gcc
CFILES=""
VALA_ARGS="" #--save-temps"
help() {
	echo "Usage: posixvala [-cChkv] [valaflags] [(vala|genie)files ...]"
	exit 0
}
for a in $@ ; do
	case "$a" in
	-h|--help) help ; ;;
	-v|--version) echo $VERSION ; exit 0 ; ;;
	-k|--save-temps) SAVETEMPS=1 ; ;;
	esac
	[ "$a" = "-c" ] && HAS_LC=1 && continue
	VALA_ARGS="${VALA_ARGS} $a"
	[ "$a" = "-C" ] && HAS_C=1
	EXT=`echo $a | cut -d . -f 2`
	case "${EXT}" in
	vala|gs)
		FILE=`echo $a|sed -e s,.${EXT},.c,`
		CFILES="${CFILES} ${FILE}"
		[ -n "`grep -e main -e ^init $a`" ] && \
			MAIN=`echo $a | sed -e s,.${EXT},,`
		;;
	esac
done
if [ "${MAIN}" = a.out ]; then
	echo "warning: unable to find main, output is a.out"
fi
${VALAC} -C ${VALA_ARGS}
R=$?; [ ! $R = 0 ] && exit $R
if [ "${HAS_C}" = 0 ]; then
	CFLAGS="${CFLAGS} -Wall -I${POSIXVALADIR} -O3"
	if [ "${HAS_LC}" = 0 ]; then
		${CC} -o ${MAIN} ${CFLAGS} ${CFILES}
	else
		${CC} -c ${CFLAGS} ${CFILES}
	fi
	R=$?; [ ! $R = 0 ] && exit $R
	[ "${SAVETEMPS}" = 0 ] && rm -f ${CFILES}
fi
exit 0
