public static const string[] sed_transform = {
	/* Provide single include file */
	"s/#include <glib\\.h>/#include <posixvala\\/runtime.h>/g",
	"s/#include <g\\(.*\\)\\.h>//g",

	/* Basic types */
	"s/TRUE/1/g",
	"s/FALSE/0/g",
	"s/gboolean/int/g",
	"s/gint/int/g",
	"s/gint16/signed short/g",
	"s/gint32/signed long/g",
	"s/gint64/signed long long/g",
	"s/guint/unsigned int/g",
	"s/gunit16/unsigned short/g",
	"s/guint32/unsigned long/g",
	"s/guint64/unsigned long long/g",
	"s/gdouble/double/g",
	"s/gfloat/float/g",
	"s/gsize/size_t/g",
	"s/gchar/char/g",
	"s/guchar/unsigned char/g",
	"s/gpointer/void \\*/g",
	"s/gconstpointer/const void \\*/g",
	"s/GType/size_t/g",
	"s/GQuark/Quark/g",
	"s/GError/Error/g",
	"s/GList/List/g",
	"s/GSList/SList/g",
	"s/GEnumValue/EnumValue/g",

	/* Function pointers */
	"s/GFunc/Func/g",
	"s/GBoxedCopyFunc/BoxedCopyFunc/g",
	"s/GBoxedFreeFunc/BoxedFreeFunc/g",
	"s/GDestroyNotify/DestroyNotify/g",

	/* Macros and functions */
	"s/ G_GNUC_CONST//g",
	"s/G_BEGIN_DECLS/#ifdef __cplusplus\\nextern \"C\" {\\n#endif/g",
	"s/G_END_DECLS/#ifdef __cplusplus\\n}\\n#endif/g",
	"s/g_once/once/g",
	"s/g_slice/slice/g",
	"s/strcmp0/strcmp/g",
	"s/g_str/str/g",
	"s/g_free/free/g",
	"s/g_new0/new0/g",
	"s/g_boxed/boxed/g",
	"s/g_quark/quark/g",
	"s/g_print/printf/g",
	"s/g_error/error/g",
	"s/g_propagate/propagate/g",
	"s/g_return/return/g",
	"s/g_list/list/g",
	"s/g_slist/slist/g",
	"s/g_crit/crit/g",
	"s/g_clear/clear/g",
	"s/g_enum/enum/g",
	"s/g_type_init ();//g",
};
